# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from ionoscloud_vm_autoscaling.models.group_policy_scale_in_action import GroupPolicyScaleInAction
from ionoscloud_vm_autoscaling.models.group_policy_scale_out_action import GroupPolicyScaleOutAction
from ionoscloud_vm_autoscaling.models.metric import Metric
from ionoscloud_vm_autoscaling.models.query_unit import QueryUnit
from typing import Optional, Set
from typing_extensions import Self

class GroupPolicy(BaseModel):
    """
    Defines the behavior of this VM Auto Scaling Group. A policy consists of triggers and actions, where an action is an automated behavior, and the trigger defines the circumstances under which the action is triggered. Currently, two separate actions are supported, namely scaling inward and outward, triggered by the thresholds defined for a particular metric.
    """ # noqa: E501
    metric: Optional[Metric] = None
    range: Optional[StrictStr] = Field(default=None, description="Specifies the time range for which the samples are to be aggregated. Must be >= 2 minutes.")
    scale_in_action: Optional[GroupPolicyScaleInAction] = Field(default=None, alias="scaleInAction")
    scale_in_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The lower threshold for the value of the 'metric'. Used with the `less than` (<) operator. When this value is exceeded, a scale-in action is triggered, specified by the 'scaleInAction' property. The value must have a higher minimum delta to the 'scaleOutThreshold', depending on the 'metric', to avoid competing for actions at the same time.", alias="scaleInThreshold")
    scale_out_action: Optional[GroupPolicyScaleOutAction] = Field(default=None, alias="scaleOutAction")
    scale_out_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The upper threshold for the value of the 'metric'. Used with the 'greater than' (>) operator. A scale-out action is triggered when this value is exceeded, specified by the 'scaleOutAction' property. The value must have a lower minimum delta to the 'scaleInThreshold', depending on the metric, to avoid competing for actions simultaneously. If 'properties.policy.unit=TOTAL', a value >= 40 must be chosen.", alias="scaleOutThreshold")
    unit: Optional[QueryUnit] = None
    __properties: ClassVar[List[str]] = ["metric", "range", "scaleInAction", "scaleInThreshold", "scaleOutAction", "scaleOutThreshold", "unit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of scale_in_action
        if self.scale_in_action:
            _dict['scaleInAction'] = self.scale_in_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scale_out_action
        if self.scale_out_action:
            _dict['scaleOutAction'] = self.scale_out_action.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metric": obj.get("metric"),
            "range": obj.get("range"),
            "scaleInAction": GroupPolicyScaleInAction.from_dict(obj["scaleInAction"]) if obj.get("scaleInAction") is not None else None,
            "scaleInThreshold": obj.get("scaleInThreshold"),
            "scaleOutAction": GroupPolicyScaleOutAction.from_dict(obj["scaleOutAction"]) if obj.get("scaleOutAction") is not None else None,
            "scaleOutThreshold": obj.get("scaleOutThreshold"),
            "unit": obj.get("unit") if obj.get("unit") is not None else QueryUnit.TOTAL
        })
        return _obj


