# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ionoscloud_vm_autoscaling.models.action_resource import ActionResource
from ionoscloud_vm_autoscaling.models.group_post_entities import GroupPostEntities
from ionoscloud_vm_autoscaling.models.group_properties import GroupProperties
from ionoscloud_vm_autoscaling.models.metadata import Metadata
from typing import Optional, Set
from typing_extensions import Self

class GroupPostResponse(BaseModel):
    """
    A group of virtual servers where the number of replicas can be scaled automatically.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The unique resource identifier.")
    type: Optional[StrictStr] = Field(default=None, description="The resource type.")
    href: Optional[StrictStr] = Field(default=None, description="The absolute URL to the resource's representation.")
    metadata: Optional[Metadata] = None
    properties: Optional[GroupProperties] = None
    entities: Optional[GroupPostEntities] = None
    started_actions: Optional[List[ActionResource]] = Field(default=None, description="Any background activity caused by this request. You can use this to track the progress of such activities.", alias="startedActions")
    __properties: ClassVar[List[str]] = ["id", "type", "href", "metadata", "properties", "entities", "startedActions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupPostResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of properties
        if self.properties:
            _dict['properties'] = self.properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of entities
        if self.entities:
            _dict['entities'] = self.entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in started_actions (list)
        _items = []
        if self.started_actions:
            for _item_started_actions in self.started_actions:
                if _item_started_actions:
                    _items.append(_item_started_actions.to_dict())
            _dict['startedActions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupPostResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "href": obj.get("href"),
            "metadata": Metadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "properties": GroupProperties.from_dict(obj["properties"]) if obj.get("properties") is not None else None,
            "entities": GroupPostEntities.from_dict(obj["entities"]) if obj.get("entities") is not None else None,
            "startedActions": [ActionResource.from_dict(_item) for _item in obj["startedActions"]] if obj.get("startedActions") is not None else None
        })
        return _obj


