# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_vm_autoscaling.models.group_policy import GroupPolicy
from ionoscloud_vm_autoscaling.models.group_properties_datacenter import GroupPropertiesDatacenter
from ionoscloud_vm_autoscaling.models.replica_properties_post import ReplicaPropertiesPost
from typing import Optional, Set
from typing_extensions import Self

class GroupProperties(BaseModel):
    """
    GroupProperties
    """ # noqa: E501
    datacenter: Optional[GroupPropertiesDatacenter] = None
    location: Optional[StrictStr] = Field(default=None, description="The data center location.")
    max_replica_count: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="The maximum value for the number of replicas. Must be >= 0 and <= 100. Will be enforced for both automatic and manual changes.", alias="maxReplicaCount")
    min_replica_count: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="The minimum value for the number of replicas. Must be >= 0 and <= 100. Will be enforced for both automatic and manual changes", alias="minReplicaCount")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The name of the VM Auto Scaling Group. This field must not be null or blank.")
    policy: Optional[GroupPolicy] = None
    replica_configuration: Optional[ReplicaPropertiesPost] = Field(default=None, alias="replicaConfiguration")
    __properties: ClassVar[List[str]] = ["datacenter", "location", "maxReplicaCount", "minReplicaCount", "name", "policy", "replicaConfiguration"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of datacenter
        if self.datacenter:
            _dict['datacenter'] = self.datacenter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of replica_configuration
        if self.replica_configuration:
            _dict['replicaConfiguration'] = self.replica_configuration.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datacenter": GroupPropertiesDatacenter.from_dict(obj["datacenter"]) if obj.get("datacenter") is not None else None,
            "location": obj.get("location"),
            "maxReplicaCount": obj.get("maxReplicaCount"),
            "minReplicaCount": obj.get("minReplicaCount"),
            "name": obj.get("name"),
            "policy": GroupPolicy.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "replicaConfiguration": ReplicaPropertiesPost.from_dict(obj["replicaConfiguration"]) if obj.get("replicaConfiguration") is not None else None
        })
        return _obj


