# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class NicFirewallRule(BaseModel):
    """
    NicFirewallRule
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The name of the firewall rule.")
    protocol: Optional[StrictStr] = Field(default=None, description="The protocol for the rule. The property cannot be modified after its creation (not allowed in update requests).")
    source_mac: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Only traffic originating from the respective MAC address is permitted. Valid format: 'aa:bb:cc:dd:ee:ff'. The value 'null' allows traffic from any MAC address.", alias="sourceMac")
    source_ip: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Only traffic originating from the respective IPv4 address is permitted. The value 'null' allows traffic from any IP address.", alias="sourceIp")
    target_ip: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="If the target NIC has multiple IP addresses, only the traffic directed to the respective IP address of the NIC is allowed. The value 'null' allows traffic to any target IP address.", alias="targetIp")
    icmp_code: Optional[Annotated[int, Field(le=254, strict=True, ge=0)]] = Field(default=None, description="Sets the allowed code (from 0 to 254) when ICMP protocol is selected. The value 'null'' allows all codes.", alias="icmpCode")
    icmp_type: Optional[Annotated[int, Field(le=254, strict=True, ge=0)]] = Field(default=None, description="Sets the allowed type (from 0 to 254) if the protocol ICMP is selected. The value 'null' allows all types.", alias="icmpType")
    port_range_start: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(default=None, description="Sets the initial range of the allowed port (from 1 to 65535) if the protocol TCP or UDP is selected. The value 'null' for 'portRangeStart' and 'portRangeEnd' allows all ports.", alias="portRangeStart")
    port_range_end: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(default=None, description="Sets the end range of the allowed port (from 1 to 65535) if the protocol TCP or UDP is selected. The value 'null' for 'portRangeStart' and 'portRangeEnd' allows all ports.", alias="portRangeEnd")
    type: Optional[StrictStr] = Field(default=None, description="The firewall rule type. If not specified, the default value 'INGRESS' is used.")
    __properties: ClassVar[List[str]] = ["name", "protocol", "sourceMac", "sourceIp", "targetIp", "icmpCode", "icmpType", "portRangeStart", "portRangeEnd", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NicFirewallRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NicFirewallRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "protocol": obj.get("protocol"),
            "sourceMac": obj.get("sourceMac"),
            "sourceIp": obj.get("sourceIp"),
            "targetIp": obj.get("targetIp"),
            "icmpCode": obj.get("icmpCode"),
            "icmpType": obj.get("icmpType"),
            "portRangeStart": obj.get("portRangeStart"),
            "portRangeEnd": obj.get("portRangeEnd"),
            "type": obj.get("type")
        })
        return _obj


