# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_vm_autoscaling.models.nic_firewall_rule import NicFirewallRule
from ionoscloud_vm_autoscaling.models.nic_flow_log import NicFlowLog
from ionoscloud_vm_autoscaling.models.target_group import TargetGroup
from typing import Optional, Set
from typing_extensions import Self

class ReplicaNic(BaseModel):
    """
    ReplicaNic
    """ # noqa: E501
    lan: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The LAN ID of this replica NIC.")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The replica NIC name.")
    dhcp: Optional[StrictBool] = Field(default=None, description="DHCP for this replica NIC. This is an optional attribute with the default value 'TRUE' if not specified in the request payload or as null.")
    firewall_active: Optional[StrictBool] = Field(default=None, description="Activate or deactivate the firewall. By default, an active firewall without any defined rules will block all incoming network traffic except for the firewall rules that explicitly allows certain protocols, IP addresses and ports.", alias="firewallActive")
    firewall_type: Optional[StrictStr] = Field(default=None, description="The type of firewall rules that will be allowed on the NIC. If not specified, the default INGRESS value is used.", alias="firewallType")
    flow_logs: Optional[List[NicFlowLog]] = Field(default=None, description="List of all flow logs for the specified NIC.", alias="flowLogs")
    firewall_rules: Optional[List[NicFirewallRule]] = Field(default=None, description="List of all firewall rules for the specified NIC.", alias="firewallRules")
    target_group: Optional[TargetGroup] = Field(default=None, alias="targetGroup")
    __properties: ClassVar[List[str]] = ["lan", "name", "dhcp", "firewallActive", "firewallType", "flowLogs", "firewallRules", "targetGroup"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplicaNic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in flow_logs (list)
        _items = []
        if self.flow_logs:
            for _item_flow_logs in self.flow_logs:
                if _item_flow_logs:
                    _items.append(_item_flow_logs.to_dict())
            _dict['flowLogs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in firewall_rules (list)
        _items = []
        if self.firewall_rules:
            for _item_firewall_rules in self.firewall_rules:
                if _item_firewall_rules:
                    _items.append(_item_firewall_rules.to_dict())
            _dict['firewallRules'] = _items
        # override the default output from pydantic by calling `to_dict()` of target_group
        if self.target_group:
            _dict['targetGroup'] = self.target_group.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplicaNic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lan": obj.get("lan"),
            "name": obj.get("name"),
            "dhcp": obj.get("dhcp"),
            "firewallActive": obj.get("firewallActive"),
            "firewallType": obj.get("firewallType"),
            "flowLogs": [NicFlowLog.from_dict(_item) for _item in obj["flowLogs"]] if obj.get("flowLogs") is not None else None,
            "firewallRules": [NicFirewallRule.from_dict(_item) for _item in obj["firewallRules"]] if obj.get("firewallRules") is not None else None,
            "targetGroup": TargetGroup.from_dict(obj["targetGroup"]) if obj.get("targetGroup") is not None else None
        })
        return _obj


