# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_vm_autoscaling.models.availability_zone import AvailabilityZone
from ionoscloud_vm_autoscaling.models.cpu_family import CpuFamily
from ionoscloud_vm_autoscaling.models.replica_nic import ReplicaNic
from ionoscloud_vm_autoscaling.models.replica_volume_post import ReplicaVolumePost
from typing import Optional, Set
from typing_extensions import Self

class ReplicaPropertiesPost(BaseModel):
    """
    ReplicaPropertiesPost
    """ # noqa: E501
    availability_zone: Optional[AvailabilityZone] = Field(default=None, alias="availabilityZone")
    cores: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The total number of cores for the VMs.")
    cpu_family: Optional[CpuFamily] = Field(default=None, alias="cpuFamily")
    nics: Optional[List[ReplicaNic]] = Field(default=None, description="The list of NICs associated with this replica.")
    ram: Optional[StrictInt] = Field(default=None, description="The size of the memory for the VMs in MB. The size must be in multiples of 256 MB, with a minimum of 256 MB; if you set 'ramHotPlug=TRUE', you must use at least 1024 MB. If you set the RAM size to more than 240 GB, 'ramHotPlug=FALSE' is fixed.")
    volumes: Optional[List[ReplicaVolumePost]] = Field(default=None, description="List of volumes associated with this Replica.")
    __properties: ClassVar[List[str]] = ["availabilityZone", "cores", "cpuFamily", "nics", "ram", "volumes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplicaPropertiesPost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nics (list)
        _items = []
        if self.nics:
            for _item_nics in self.nics:
                if _item_nics:
                    _items.append(_item_nics.to_dict())
            _dict['nics'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                if _item_volumes:
                    _items.append(_item_volumes.to_dict())
            _dict['volumes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplicaPropertiesPost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "availabilityZone": obj.get("availabilityZone"),
            "cores": obj.get("cores"),
            "cpuFamily": obj.get("cpuFamily"),
            "nics": [ReplicaNic.from_dict(_item) for _item in obj["nics"]] if obj.get("nics") is not None else None,
            "ram": obj.get("ram"),
            "volumes": [ReplicaVolumePost.from_dict(_item) for _item in obj["volumes"]] if obj.get("volumes") is not None else None
        })
        return _obj


