# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_vm_autoscaling.models.bus_type import BusType
from ionoscloud_vm_autoscaling.models.volume_hw_type import VolumeHwType
from typing import Optional, Set
from typing_extensions import Self

class ReplicaVolumePost(BaseModel):
    """
    ReplicaVolumePost
    """ # noqa: E501
    image: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The image installed on the disk. Currently, only the UUID of the image is supported.  >Note that either 'image' or 'imageAlias' must be specified, but not both.")
    image_alias: Optional[StrictStr] = Field(default=None, description="The image installed on the volume. Must be an 'imageAlias' as specified via the images API. Note that one of 'image' or 'imageAlias' must be set, but not both.", alias="imageAlias")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The replica volume name.")
    size: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The size of this replica volume in GB.")
    ssh_keys: Optional[List[StrictStr]] = Field(default=None, description="The SSH keys of this volume.", alias="sshKeys")
    type: Optional[VolumeHwType] = None
    user_data: Optional[StrictStr] = Field(default=None, description="The user data (Cloud Init) for this replica volume.", alias="userData")
    bus: Optional[BusType] = None
    backupunit_id: Optional[StrictStr] = Field(default=None, description="The ID of the backup unit that the user has access to. The property is immutable and is only allowed to be set on creation of a new a volume. It is mandatory to provide either 'public image' or 'imageAlias' in conjunction with this property.", alias="backupunitId")
    boot_order: Optional[StrictStr] = Field(default=None, description="Determines whether the volume will be used as a boot volume. Set to NONE, the volume will not be used as boot volume. Set to PRIMARY, the volume will be used as boot volume and set to AUTO will delegate the decision to the provisioning engine to decide whether to use the voluem as boot volume. Notice that exactly one volume can be set to PRIMARY or all of them set to AUTO.", alias="bootOrder")
    image_password: Optional[StrictStr] = Field(default=None, description="The image password for this replica volume.", alias="imagePassword")
    __properties: ClassVar[List[str]] = ["image", "imageAlias", "name", "size", "sshKeys", "type", "userData", "bus", "backupunitId", "bootOrder", "imagePassword"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplicaVolumePost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplicaVolumePost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "image": obj.get("image"),
            "imageAlias": obj.get("imageAlias"),
            "name": obj.get("name"),
            "size": obj.get("size"),
            "sshKeys": obj.get("sshKeys"),
            "type": obj.get("type"),
            "userData": obj.get("userData"),
            "bus": obj.get("bus") if obj.get("bus") is not None else BusType.VIRTIO,
            "backupunitId": obj.get("backupunitId"),
            "bootOrder": obj.get("bootOrder"),
            "imagePassword": obj.get("imagePassword")
        })
        return _obj


