# coding: utf-8

"""
    VM Auto Scaling API

    The VM Auto Scaling Service enables IONOS clients to horizontally scale the number of VM replicas based on configured rules. You can use VM Auto Scaling to ensure that you have a sufficient number of replicas to handle your application loads at all times.  For this purpose, create a VM Auto Scaling Group that contains the server replicas. The VM Auto Scaling Service ensures that the number of replicas in the group is always within the defined limits.   When scaling policies are set, VM Auto Scaling creates or deletes replicas according to the requirements of your applications. For each policy, specified 'scale-in' and 'scale-out' actions are performed when the corresponding thresholds are reached.

    The version of the OpenAPI document: 1.0.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VolumeHwType(str, Enum):
    """
    The storage type of this replica volume (SSD or HDD).
    """

    """
    allowed enum values
    """
    HDD = 'HDD'
    SSD = 'SSD'
    SSD_PREMIUM = 'SSD_PREMIUM'
    SSD_STANDARD = 'SSD_STANDARD'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VolumeHwType from a JSON string"""
        return cls(json.loads(json_str))


